ignore_shipment:
  fields:
    tracking_number:
      required: true
      example: "1050799150127U"
      selector:
        text:

unignore_shipment:
  fields:
    tracking_number:
      required: true
      example: "1050799150127U"
      selector:
        text:

track_shipment:
  fields:
    tracking_number:
      required: true
      example: "520100019331571009344789"
      selector:
        text:
